const base = '/api/v1'
async function req(path, opts = {}) {
  const res = await fetch(base + path, {
    headers: { 'Content-Type': 'application/json' }, credentials: 'same-origin',
    ...opts, body: opts.body ? JSON.stringify(opts.body) : undefined
  })
  const text = await res.text(); const data = text ? JSON.parse(text) : null
  if (!res.ok) throw new Error(data?.error || `Lỗi ${res.status}`)
  return { data, cache: res.headers.get('X-Cache') }
}
export const api = {
  dashboard: () => req('/dashboard'),
  products: () => req('/products'),
  createProduct: (b) => req('/products', { method: 'POST', body: b }),
  importPim: () => req('/products/import-pim', { method: 'POST' }),
  units: (q) => req(`/units${q ? `?q=${encodeURIComponent(q)}` : ''}`),
  unit: (id) => req(`/units/${id}`),
  createUnit: (b) => req('/units', { method: 'POST', body: b }),
  addEvent: (id, b) => req(`/units/${id}/events`, { method: 'POST', body: b }),
  trace: (code) => req(`/trace/${encodeURIComponent(code)}`),
  verify: (b) => req('/verify', { method: 'POST', body: b }),
  verifications: (q) => req(`/verifications${q ? `?q=${encodeURIComponent(q)}` : ''}`),
  ctes: (q) => req(`/ctes${q ? `?q=${encodeURIComponent(q)}` : ''}`),
  saveCte: (b) => req('/ctes', { method: 'POST', body: b }),
  deleteCte: (id) => req(`/ctes/${id}`, { method: 'DELETE' }),
  kdes: (q) => req(`/kdes${q ? `?q=${encodeURIComponent(q)}` : ''}`),
  saveKde: (b) => req('/kdes', { method: 'POST', body: b }),
  deleteKde: (id) => req(`/kdes/${id}`, { method: 'DELETE' }),
  dataTypes: (q) => req(`/data-types${q ? `?q=${encodeURIComponent(q)}` : ''}`),
  saveDataType: (b) => req('/data-types', { method: 'POST', body: b }),
  deleteDataType: (id) => req(`/data-types/${id}`, { method: 'DELETE' }),
  cteKdes: (cteCode) => req(`/cte-kdes${cteCode ? `?cteCode=${encodeURIComponent(cteCode)}` : ''}`),
  saveCteKdes: (b) => req('/cte-kdes', { method: 'POST', body: b }),
  glns: (q) => req(`/glns${q ? `?q=${encodeURIComponent(q)}` : ''}`),
  saveGln: (b) => req('/glns', { method: 'POST', body: b }),
  deleteGln: (id) => req(`/glns/${id}`, { method: 'DELETE' }),
  farms: (q) => req(`/farms${q ? `?q=${encodeURIComponent(q)}` : ''}`),
  saveFarm: (b) => req('/farms', { method: 'POST', body: b }),
  deleteFarm: (id) => req(`/farms/${id}`, { method: 'DELETE' }),
  marketAreas: (q) => req(`/market-areas${q ? `?q=${encodeURIComponent(q)}` : ''}`),
  saveMarketArea: (b) => req('/market-areas', { method: 'POST', body: b }),
  deleteMarketArea: (id) => req(`/market-areas/${id}`, { method: 'DELETE' }),
  orgGlns: (q) => req(`/org-glns${q ? `?q=${encodeURIComponent(q)}` : ''}`),
  saveOrgGln: (b) => req('/org-glns', { method: 'POST', body: b }),
  deleteOrgGln: (id) => req(`/org-glns/${id}`, { method: 'DELETE' }),
  templates: (q) => req(`/templates${q ? `?q=${encodeURIComponent(q)}` : ''}`),
  template: (id) => req(`/templates/${id}`),
  saveTemplate: (b) => req('/templates', { method: 'POST', body: b }),
  approveTemplate: (id) => req(`/templates/${id}/approve`, { method: 'POST' }),
  deleteTemplate: (id) => req(`/templates/${id}`, { method: 'DELETE' }),
  tplViewEvents: (q) => req(`/tpl-view-events${q ? `?q=${encodeURIComponent(q)}` : ''}`),
  saveTplViewEvent: (b) => req('/tpl-view-events', { method: 'POST', body: b }),
  deleteTplViewEvent: (id) => req(`/tpl-view-events/${id}`, { method: 'DELETE' }),
  records: (q) => req(`/records${q ? `?q=${encodeURIComponent(q)}` : ''}`),
  record: (id) => req(`/records/${id}`),
  saveRecord: (b) => req('/records', { method: 'POST', body: b }),
  deleteRecord: (id) => req(`/records/${id}`, { method: 'DELETE' }),
  stampBatches: (q) => req(`/stamp-batches${q ? `?q=${encodeURIComponent(q)}` : ''}`),
  stampBatch: (id) => req(`/stamp-batches/${id}`),
  generateStamps: (b) => req('/stamp-batches', { method: 'POST', body: b }),
  deleteStampBatch: (id) => req(`/stamp-batches/${id}`, { method: 'DELETE' }),
  stamps: (batchId, q) => req(`/stamps?${batchId ? `batchId=${batchId}&` : ''}${q ? `q=${encodeURIComponent(q)}` : ''}`),
  boxes: (q) => req(`/boxes${q ? `?q=${encodeURIComponent(q)}` : ''}`),
  box: (id) => req(`/boxes/${id}`),
  createBox: (b) => req('/boxes', { method: 'POST', body: b }),
  addStampsToBox: (id, b) => req(`/boxes/${id}/stamps`, { method: 'POST', body: b }),
  deleteBox: (id) => req(`/boxes/${id}`, { method: 'DELETE' }),
  cartons: (q) => req(`/cartons${q ? `?q=${encodeURIComponent(q)}` : ''}`),
  carton: (id) => req(`/cartons/${id}`),
  createCarton: (b) => req('/cartons', { method: 'POST', body: b }),
  addBoxesToCarton: (id, b) => req(`/cartons/${id}/boxes`, { method: 'POST', body: b }),
  deleteCarton: (id) => req(`/cartons/${id}`, { method: 'DELETE' }),
  queSyncs: (q) => req(`/que-syncs${q ? `?q=${encodeURIComponent(q)}` : ''}`),
  saveQueSync: (b) => req('/que-syncs', { method: 'POST', body: b }),
  markQueSync: (id, b) => req(`/que-syncs/${id}/mark`, { method: 'POST', body: b }),
  deleteQueSync: (id) => req(`/que-syncs/${id}`, { method: 'DELETE' }),
  masterDatas: (q) => req(`/master-datas${q ? `?q=${encodeURIComponent(q)}` : ''}`),
  saveMasterData: (b) => req('/master-datas', { method: 'POST', body: b }),
  deleteMasterData: (id) => req(`/master-datas/${id}`, { method: 'DELETE' }),
  networkOrgs: (q) => req(`/network-orgs${q ? `?q=${encodeURIComponent(q)}` : ''}`),
  saveNetworkOrg: (b) => req('/network-orgs', { method: 'POST', body: b }),
  registerNetworkOrg: (id) => req(`/network-orgs/${id}/register`, { method: 'POST' }),
  deleteNetworkOrg: (id) => req(`/network-orgs/${id}`, { method: 'DELETE' }),
  secrets: (q, used) => req(`/secrets?${used !== undefined && used !== null ? `used=${used}&` : ''}${q ? `q=${encodeURIComponent(q)}` : ''}`),
  saveSecret: (b) => req('/secrets', { method: 'POST', body: b }),
  markSecretUsed: (id) => req(`/secrets/${id}/use`, { method: 'POST' }),
  deleteSecret: (id) => req(`/secrets/${id}`, { method: 'DELETE' }),
  stampPairs: (q) => req(`/stamp-pairs${q ? `?q=${encodeURIComponent(q)}` : ''}`),
  saveStampPair: (b) => req('/stamp-pairs', { method: 'POST', body: b }),
  deleteStampPair: (id) => req(`/stamp-pairs/${id}`, { method: 'DELETE' }),
  productIds: (q) => req(`/product-ids${q ? `?q=${encodeURIComponent(q)}` : ''}`),
  productId: (id) => req(`/product-ids/${id}`),
  saveProductId: (b) => req('/product-ids', { method: 'POST', body: b }),
  deleteProductId: (id) => req(`/product-ids/${id}`, { method: 'DELETE' }),
  configColumnSearches: (q) => req(`/config-column-searches${q ? `?q=${encodeURIComponent(q)}` : ''}`),
  saveConfigColumnSearch: (b) => req('/config-column-searches', { method: 'POST', body: b }),
  deleteConfigColumnSearch: (id) => req(`/config-column-searches/${id}`, { method: 'DELETE' }),
  manufacturedIds: (q) => req(`/manufactured-ids${q ? `?q=${encodeURIComponent(q)}` : ''}`),
  saveManufacturedId: (b) => req('/manufactured-ids', { method: 'POST', body: b }),
  deleteManufacturedId: (id) => req(`/manufactured-ids/${id}`, { method: 'DELETE' }),
  networkMasters: (q) => req(`/network-masters${q ? `?q=${encodeURIComponent(q)}` : ''}`),
  saveNetworkMaster: (b) => req('/network-masters', { method: 'POST', body: b }),
  deleteNetworkMaster: (id) => req(`/network-masters/${id}`, { method: 'DELETE' }),
  distributionHistories: (q, refType) => req(`/distribution-histories?${refType !== undefined && refType !== null ? `refType=${refType}&` : ''}${q ? `q=${encodeURIComponent(q)}` : ''}`),
  saveDistributionHistory: (b) => req('/distribution-histories', { method: 'POST', body: b }),
  deleteDistributionHistory: (id) => req(`/distribution-histories/${id}`, { method: 'DELETE' }),
  dealers: (q) => req(`/dealers${q ? `?q=${encodeURIComponent(q)}` : ''}`),
  saveDealer: (b) => req('/dealers', { method: 'POST', body: b }),
  deleteDealer: (id) => req(`/dealers/${id}`, { method: 'DELETE' }),
  manufactureLines: (q) => req(`/manufacture-lines${q ? `?q=${encodeURIComponent(q)}` : ''}`),
  saveManufactureLine: (b) => req('/manufacture-lines', { method: 'POST', body: b }),
  deleteManufactureLine: (id) => req(`/manufacture-lines/${id}`, { method: 'DELETE' }),
  warningSyncESs: (q, status) => req(`/warning-sync-es?${status !== undefined && status !== null ? `status=${status}&` : ''}${q ? `q=${encodeURIComponent(q)}` : ''}`),
  saveWarningSyncES: (b) => req('/warning-sync-es', { method: 'POST', body: b }),
  markWarningSyncES: (id, b) => req(`/warning-sync-es/${id}/mark`, { method: 'POST', body: b }),
  deleteWarningSyncES: (id) => req(`/warning-sync-es/${id}`, { method: 'DELETE' }),
  provinces: (q) => req(`/provinces${q ? `?q=${encodeURIComponent(q)}` : ''}`),
  saveProvince: (b) => req('/provinces', { method: 'POST', body: b }),
  deleteProvince: (id) => req(`/provinces/${id}`, { method: 'DELETE' }),
  notifyForSearches: (q) => req(`/notify-for-searches${q ? `?q=${encodeURIComponent(q)}` : ''}`),
  saveNotifyForSearch: (b) => req('/notify-for-searches', { method: 'POST', body: b }),
  deleteNotifyForSearch: (id) => req(`/notify-for-searches/${id}`, { method: 'DELETE' })
}
export const fmtDate = (s) => s ? new Date(s).toLocaleDateString('vi-VN') : '—'
export const fmtDateTime = (s) => s ? new Date(s).toLocaleString('vi-VN') : '—'
export const STAGES = ['Sản xuất', 'Kiểm định', 'Đóng gói', 'Nhập kho', 'Vận chuyển', 'Đại lý nhận', 'Bày bán', 'Đã bán']
